### ISSUE TITLE
issue regarding analysis

### ISSUE THREAD

**Issue by Aswathy321** [Aswathy321/issue#1]
# issue
About Dataset -
Had fetched risk type data for  timestamp from november 2021 to december.
Then find out cobble epochs for specific period and match the cobble epochs with timestamps prior to 1 hour.
 Thus new dataframe includes risk type data for ~ 20 tags and a target column with 1's and 0's , where time stamps > or prior to 1 hour is denoted as 1 and remaining as 0.
Aim -
 Using available dataset need to built a confusion matrix, so that will get an idea about False negatives and False positives among them, like to detect high risk values where matching cobbles will not present and low risk values having matching cobbles present.
 
I wanted to know what approach should taken for splitting of feature variables and target variables for plotting according to the purpose.

**Comment by Aswathy321** [comment]
@arun-es

**Comment by arun-es** [comment]
is this risk or the shapes?

**Comment by Aswathy321** [comment]
risk data

**Comment by arun-es** [comment]
1. Identify all time periods of cobble
2. Get data 2 hours prior to failure
3. Data 1 hour prior to failure is marked as 1, the previous hour is marked as 0
4. Find median of each column for each of these two periods M1 and M2
5. Find IQR of risk for each period
6. calculate Z = abs(M2 - M1) / IQR for each tag, for each cobble
7. assign a rank for each tag as 1 to N, where N is the number of variables. rank 1 = highest Z, rank N = lowest Z
8. After processing all tags, find tags that have a rank above N/2

**Comment by Aswathy321** [comment]
so the tags above N/2 have low risk,Is it like that ?

**Comment by arun-es** [comment]
they will have higher change of risk

**Comment by Aswathy321** [comment]
related to the range of IQR

**Comment by arun-es** [comment]
yes, normalizing

**Comment by Aswathy321** [comment]
Had  found out ranks of each tags corresponds to 'Z' value for each cobble epoch. Shared a google slide with description.
Hereafter, What approach have to taken  for further analysis and to figure out false positive/false negative in terms of cobble epochs and risk factor

**Comment by Aswathy321** [comment]
Had completed risk data analysis and includes  summation of total rank for each tag on google slides. 
Need to know further analysis approach need to be taken .

**Comment by Aswathy321** [comment]
@arun-es

**Comment by arun-es** [comment]
Ideally open this issue inside the official cobble detect repo. this is currently in your personal repo.
